name: Build PDF

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup TeX Live
      uses: xu-cheng/latex-action@v2
      with:
        root_file: Appendix.tex

    - name: Compile LaTeX document
      run: pdflatex Appendix.tex

    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: Compiled-PDF
        path: Appendix.pdf
